### ISSUE TITLE
WARNING： SQL injection

### ISSUE THREAD

**Issue by jinyu121** [billchenchina/UOJ-Edited#8]
Position: `app/controllers/super_manage.php` , changing user info
How to test: 
    Change `school` into `'` ans submit
    Expect: The school of user changed to `'`
    Now: Nothing

Reason: 
    We use RAW SQL with SIMPLE STRING CONCAT here. `'` ends the sql, and raise an error. So, if we use `' delete from user_info; -- `, all user will be delete.

SOLUTION:
    Use `placeholder` if any. I know JAVA have this thing. Or, use `User` CLASS, rather than RAW SQL.

**Comment by billchenchina** [comment]
@jinyu121 Thanks, will fix soon.

**Comment by billchenchina** [comment]
@jinyu121 Cant reproduce in my environment.

**Comment by jinyu121** [comment]
https://github.com/BIDGroup/UOJ-Edu/blob/master/app/controllers/super_manage.php#L62

Well... If school, grade, or realname contains `'`, it will end the left `'`. For example, school is `XX'XX`, contains `'`, so the SQL will be `"update user_info set school = 'XX'XX',grade ='XXX',real_name ='XXX'where username ='XXX'")`

It is a wrong SQL. So it will  not be run. 

Another assumption:school=`'; delete from user_info; --`

The SQL will be `"update user_info set school = ''; delete from user_info; --',grade ='XXX',real_name ='XXX'where username ='XXX'`, and that's three SQLs:

+ `update user_info set school = '';` will make school empty to all user
+ `delete from user_info;` You know what I mean
+ `--',grade ='XXX',real_name ='XXX'where username ='XXX'` will be ignored

**Comment by billchenchina** [comment]
@jinyu121 Still couldnt reproduce. @igronemyk

**Comment by billchenchina** [comment]
@jinyu121 It seems that the mysql query string automatically escaped in my environment.

Queries including a single `'` couldnt run, including double `'` is escaped.

**Comment by billchenchina** [comment]
Check this out.

https://github.com/universaloj-test/install-scripts/tree/master/pre-install

Here are some config files that describes my environment, perhaps you need to update your config.
